apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app
  namespace: quote-lab
spec:
  replicas: 3 # On commence avec 3 pour montrer le scaling
  selector:
    matchLabels:
      app: quote-app
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      #permet de garder les 3 good  
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: quote-app
    spec:
      containers:
        - name: quote-app
          image: quote-app:v2
          imagePullPolicy: Never

          ports:
            - containerPort: 3000

          env:
            - name: PORT
              value: "3000"
            - name: HOST
              value: "0.0.0.0"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: quote-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quote-db-secret
                  key: POSTGRES_PASSWORD

          # --- Section Extension Lane E: Resource Management ---
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"

          # --- Validation du comportement Runtime (Probes) ---
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
